AWSTemplateFormatVersion: "2010-09-09"
Description: vpc nested stack
Parameters:
  VpcBlock:
    Type: String
    Default: 10.0.0.0/16
    Description: vpc cidr range
  Subnet01Block:
    Type: String
    Default: 10.0.1.0/24


Metadata:
  AWS::Cloudformation::Interface:
    ParametersGroup:
      - Label:
          default: Dev vpc config
        Parameters:
          - VpcBlock
          - Subnet01Block
    ParametersLabel:
      VpcBlock:
        default: vpc cidr block Select


Resources:
  VPCLearning:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: !Ref VpcBlock
        EnableDnsHostnames: true
        EnableDnsSupport: true
        # Tags:
        #   - key: name
        #     Value: !Sub "${AWS::StackName}-VPCLearning"

  Subnet01:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - "0"
          - Fn::GetAZs:
              Ref: AWS::Region

      CidrBlock: !Ref Subnet01Block
      VpcId: !Ref VPCLearning
      # Tags:
      #   - Key: name
      #     Value: !Sub "${AWS::StackName}-Subnet01"

  Routing:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPCLearning
      # Tags:
      #   - key : name
      #     Value: Public subnet


  SubentRouteAss:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet01
      RouteTableId: !Ref Routing


  IGW:
    Type: AWS::EC2::InternetGateway

  VPCgatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref IGW
      VpcId: !Ref VPCLearning

  RouteOut:
    DependsOn : VPCgatewayAttachment
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref Routing
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW


Outputs:
  Subnet01Id:
    Description: subnet01Id is here
    Value: !Ref Subnet01
  VpcID:
    Description: vpcid
    Value: !Ref VPCLearning
