AWSTemplateFormatVersion: "2010-09-09"

Resources:
  MyVmInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - RegionArray
        - !Ref "AWS::Region"
        - HVM64
      InstanceType: !FindInMap
        - InstanceAvailable
        - !Ref EnvironmentAvailble
        - intance
      UserData:
        Fn::Base64: |
          #!bin/bash
          sudo yum update
          sudo yum -y install httpd
          sudo yum -y install tomcat8
          service tomcat8 start
          mkdir /usr/share/tomcat8/webapps/ROOT
          touch /usr/share/tomcat8/webapps/ROOT/index.html
          echo "cloudformation template" > /usr/share/tomcat8/webapps/ROOT/index.html



Outputs:
  MyInstanceID:
    Description: My instance id
    Value: !Ref MyVmInstance

  MyDNSName:
    Description: get public dns name
    Value: !GetAtt MyVmInstance.PublicDnsName
  AppURL:
    Description: application of the tomcat8
    Value: !Sub "http//${MyVmInstance.PublicDnsName}:8080/index.html"
  # MyInstanceAvailibityZone:
  #   Description: Get instance availavlbity zone
  #   Value: !GetAtt


Mappings:
  RegionArray:
    us-east-1:
      HVM64: "ami-0ff8a91507f77f867"
      HVMG2: "ami-0a584ac55a7631c0c"
    us-west-1:
      HVM64: "ami-0bdb828fd58c52235"
      HVMG2: "ami-066ee5fd4a9ef77f1"
    eu-west-1:
      HVM64: "ami-047bb4163c506cd98"
      HVMG2: "ami-31c2f645"
    ap-southeast-1:
      HVM64: "ami-08569b978cc4dfa10"
      HVMG2: "ami-0be9df32ae9f92309"
    ap-northeast-1:
      HVM64: "ami-06cd52961ce9f0d85"
      HVMG2: "ami-053cdd503598e4a9d"

  InstanceAvailable:
    Dev:
      intance: t2.micro
    Prod:
      intance: t2.medium


Parameters:
  EnvironmentAvailble:
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Prod
